name: OSVVM Regression FIFO with GHDL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  osvvm-ghdl-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (GHDL with LLVM backend, Tcl, Tcllib)
        run: |
          sudo apt update
          sudo apt install -y git build-essential \
            llvm-14 llvm-14-dev llvm-14-tools \
            zlib1g-dev gnat tcl tcllib

      - name: Build and install GHDL with LLVM backend
        run: |
          git clone https://github.com/ghdl/ghdl.git
          cd ghdl
          ./configure --with-llvm-config=llvm-config-14
          make -j$(nproc)
          sudo make install
          cd ..
          ghdl --version

      # Regression tests with failure handling
      - name: Run OSVVM regression_axi4_olo.tcl
        run: tclsh script/regression_axi4_olo.tcl || exit 1

      - name: Run OSVVM regression_axi4_python
        run: tclsh script/regression_axi4_python.tcl || exit 1

      - name: Run OSVVM regression_axi4_stream.tcl
        run: tclsh script/regression_axi4_stream.tcl || exit 1

      - name: Run OSVVM regression_stream_image_inv.tcl
        run: tclsh script/regression_stream_image_inv.tcl || exit 1

      - name: Run OSVVM regression_fifo.tcl
        run: tclsh script/regression_fifo.tcl || exit 1

      - name: Run OSVVM regression_stream_delta.tcl
        run: tclsh script/regression_stream_delta.tcl || exit 1

      - name: Run OSVVM frame_gen__fifo.tcl
        run: tclsh script/regression_frame_gen.tcl || exit 1
        
      - name: Run OSVVM axi_lite_4
        run: tclsh script/regression_axi4.tcl || exit 1

      - name: Upload simulation results (optional)
        if: success()  # Only upload if all previous steps succeeded
        uses: actions/upload-artifact@v4
        with:
          name: simulation-results
          path: |
            **/*.ghw
            **/*.vcd
            ./